const mockFarmerRecords = [
  {
    id: 'FRM2387',
    name: 'Ramesh Kumar',
    district: 'Sehore',
    landSize: '2.4 acres',
    cropType: 'Wheat',
    fertilizerType: 'Urea',
    purchases: 7,
    fertilizerPurchasedKg: 1850,
    districtAverageKg: 580,
    dealersUsed: 4,
    status: 'Active',
    lastPurchase: '2025-05-26',
    monthlyLimitKg: 700,
    previous30DayAvgKg: 540,
    transactionHistory: [],
  },
  {
    id: 'FRM1003',
    name: 'Mohan Lal',
    district: 'Raisen',
    landSize: '1.8 acres',
    cropType: 'Soybean',
    fertilizerType: 'DAP',
    purchases: 6,
    fertilizerPurchasedKg: 1320,
    districtAverageKg: 520,
    dealersUsed: 3,
    status: 'Active',
    lastPurchase: '2025-05-25',
    monthlyLimitKg: 600,
    previous30DayAvgKg: 460,
    transactionHistory: [],
  },
  {
    id: 'FRM4582',
    name: 'Sita Devi',
    district: 'Vidisha',
    landSize: '3.1 acres',
    cropType: 'Wheat',
    fertilizerType: 'Urea',
    purchases: 4,
    fertilizerPurchasedKg: 710,
    districtAverageKg: 590,
    dealersUsed: 2,
    status: 'Active',
    lastPurchase: '2025-05-24',
    monthlyLimitKg: 750,
    previous30DayAvgKg: 700,
    transactionHistory: [],
  },
  {
    id: 'FRM7731',
    name: 'Shyam Singh',
    district: 'Hoshangabad',
    landSize: '1.5 acres',
    cropType: 'Paddy',
    fertilizerType: 'DAP',
    purchases: 5,
    fertilizerPurchasedKg: 980,
    districtAverageKg: 430,
    dealersUsed: 1,
    status: 'Inactive',
    lastPurchase: '2025-05-23',
    monthlyLimitKg: 500,
    previous30DayAvgKg: 420,
    transactionHistory: [],
  },
  {
    id: 'FRM9012',
    name: 'Vijay Patel',
    district: 'Sehore',
    landSize: '2.0 acres',
    cropType: 'Wheat',
    fertilizerType: 'Urea',
    purchases: 3,
    fertilizerPurchasedKg: 560,
    districtAverageKg: 580,
    dealersUsed: 1,
    status: 'Active',
    lastPurchase: '2025-05-22',
    monthlyLimitKg: 650,
    previous30DayAvgKg: 540,
    transactionHistory: [],
  },
  {
    id: 'FRM1208',
    name: 'Kamla Bai',
    district: 'Raisen',
    landSize: '2.7 acres',
    cropType: 'Soybean',
    fertilizerType: 'NPK 20:20:0:13',
    purchases: 8,
    fertilizerPurchasedKg: 1490,
    districtAverageKg: 500,
    dealersUsed: 3,
    status: 'Active',
    lastPurchase: '2025-05-26',
    monthlyLimitKg: 650,
    previous30DayAvgKg: 520,
    transactionHistory: [],
  },
];

export default mockFarmerRecords;
